index.js
readme.md
test.js

Fixes #9 
adds `throwHttpErrors` option defaulted to `true` along with updated docs and tests.

Add `throwHttpErrors` option

---

index.js
test/_require.js

Currently, ky cannot be used in web workers because workers don't have a global `window` object. However, all globals used in ky (namely `Headers` and `fetch`) are also available on a worker's `self` scope.
Since `self` also points to the global object in the browser, this PR replaces all occurrences of `window` with `self`, so ky can be used in browsers and web workers alike.

Support Ky usage in web workers

---

cypress/integration/index.js
index.js
test/_require.js

Fixes https://github.com/sindresorhus/ky/issues/58
There was a regression introduced in https://github.com/sindresorhus/ky/commit/a7c71b5728adb5efab59f4057caf83a82453ba4d which broke the ability for `input` to be a relative URL like `foo` or `/foo`. The root cause is that [`window.URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL) unfortunately does not support relative URLs without an explicit and absolute `base` argument. This fixes that and adds a test for it. Now that we have Cypress set up, we can properly test anything related to relative URLs.
The goal is to follow the URL resolution rules the same way that `fetch` does. So we resolve `input` against [`document.baseURI`](https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI#The_base_URL_of_a_document).

Fix relative URL resolution

---

index.js
readme.md
test/methods.js

According to [Fetch specifications](https://fetch.spec.whatwg.org/#concept-method-normalize), method name normalization is currently applied to all but `PATCH`. I personally use this library but in this case, I must override the `method` option in order to fix the issue.
This proposal normalizes shorthand `method` option.

Normalize `method` option value casing

---

.travis.yml
index.js
test/_require.js
test/hooks.js
test/main.js

Fixes #64 
This is similar to PR #69, however I've taken a different approach. Some of my goals include:
- No regex testing of URLs.
- Let `fetch()` handle URL resolution where possible.
- Guard against `ReferenceError`s by not accessing globals when we don't need them.
- Simplify testing and mocking by treating `global`, `window`, and `self` as not mutually exclusive.
This should make things significantly easier in non-browser environments. In my testing on Node 10+, I was able to remove everything except for `fetch` and `Response` in [test/_require.js](https://github.com/sindresorhus/ky/blob/master/test/_require.js) and the test suite passed.
Previously, Ky would find the global object and then assume everything lived on that object, which makes things cumbersome in non-DOM / no-browser …

Avoid use of globals where possible

---

index.js
test/main.js

Here is a bug:
When I set `throwHttpErrors` to `false` and then `POST` a request, if the response is not OK, it will still throw `HTTPError`. So I fixed it.

Fix the `throwHttpErrors` option for POST requests

---

.gitignore
package.json
readme.md

Closes #44 
Following the discussions in #44 and #46, we decided to only convert module syntax. This does not transpile the code to ES5, so extremely old environments are still not supported out of the box. Rather, this makes it easy to import ky in non-ESM environments, such as Node.js.
I went with Rollup instead of Babel, because it is simpler to configure and its output is slightly better (easier to read 👀 and no hardcoded AMD ID).

Add a UMD build to support older environments

---

index.d.ts
index.test-d.ts

Hopefully a JSON type will be included in TypeScript at some point: https://github.com/Microsoft/TypeScript/issues/1897 For now, we just define it manually.

Use more specific JSON types in TypeScript

---

index.js
package.json
readme.md

I wanted to run Ky in [Deno](https://github.com/denoland/deno). Turns out it works, with the only blocker being that Deno uses `globalThis` instead of `global`. Annoying, but Deno is just [following standards](https://github.com/tc39/proposal-global).
Should we officially advertise support for it? I don't know. But I am so excited about Deno. And since the code is super simple, I figured I'd at least propose it. :)

Support running Ky in Deno

---

index.d.ts
index.test-d.ts

It can still be used as before without a generic.
Fixes #80

Make the `.json()` method generic

---

index.d.ts
index.js
index.test-d.ts
test/main.js

Improve type system for get and head methods

---

readme.md

It took me a long time until I understood what that sentence actually meant, until I saw the `json()` used in other examples. It's VERY easy to overlook, so making this small modification goes a long way for newbies to understand this sentence much better!!

Clarify usage of `.json()`

---

index.d.ts
index.test-d.ts

Fixes #112 
Adds `constructor` definitions for both `HTTPError` and `TimeoutError`

Fix Error types

---

index.js

Fixes #91
As discussed in #91 the `TimeoutError` is thrown unconditionally in at least two major browsers. This should only happen if the request hadn’t completed before the timeout. 
Note from @szmarczak: provided a shorter workaround.

Fix problem with debugging timed-out requests

---

index.js

#122 removed the check on whether `abortController` exists before calling `abort()`.
This fixes this check for platforms that don't support abortController (e.g. react-native)

Fix regression for environments without `AbortController`

---

index.js
readme.md
test/methods.js

closes #83 
I was first thinking about conditionally setting this inside `ky`s constructor, but it would mean more complexity, as there's no way to know whether the method is set by calling shortcut method or not. We get this for free in `createInstance` function, where shortcut methods are generated, and where I eventually decided to set the header.

Set accept header for ky shortcut methods

---

index.d.ts
index.js
readme.md
test/main.js

Limit maximum timeout, add timeout: false option, fixes #117

Implement disabling timeouts

---

index.js
test/main.js

Remaining timeout prevents node from terminating the process. These changes clear the timeout on promise resolution.
Closes https://github.com/sindresorhus/ky/issues/138

Fix timeout regression that caused Node.js to not terminate

---

index.d.ts
index.test-d.ts

The union of `OptionsWithBody` and `OptionsWithoutBody`, both not exported, makes it impossible to reuse an options like so:
```ts
const options: Options = {
method: 'get'
};
ky(url, options);
```
or if you want to wrap `ky` in your own function:
```ts
function httpClient(input: Input, options: Options) {
return ky(input, options);
}
```
Given that you can't assign the default `string` method (defined in `Options`) to `'get' | 'head' | 'post' | ...'` expected by the `ky` function.
Thus, I've exported and refactored both the `Input` and `Options` that make the API of `ky` so one can reuse without conflicts.
----
However, the decision to group these two types of options has the drawback of not supporting other custom HTTP methods (e.g. `trace`, `my-custom-method`). That was already the …

Fix the options TypeScript type

---

index.d.ts
index.test-d.ts

`hooks.beforeRequest` hooks do not receive `Options` but a new set of normalized options with a combination of fetch and ky options, plus a more strict `headers` type.
Re: https://github.com/sindresorhus/ky/issues/139

Fix the `BeforeRequestHook` TypeScript type

---

index.d.ts
index.test-d.ts

Fixes #164 
See discussion in issue above.
This PR:
* makes reusing, extending and manipulating `Options` type more flexible;
* adds support for custom HTTP verbs/methods;
* aligns `ky`'s API with the native `fetch`.

Simplify the `Options` TypeScript type

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js
test/methods.js

I needed to access `input` and `options` on `afterResponse` hook to perform retry with a fresh access  token like:
```js
import ky from 'ky';
(async () => {
await ky.get('https://example.com', {
hooks: {
afterResponse: [
async (input, options, response) => {
if (response.status === 403) {
// Get a fresh token
const token = await ky.get('https://example.com/token').text();
// Retry with the token
options.headers.set('Authorization', `token ${token}`);
return ky(input,  {
...options,
});
}
}
]
}
});
})();
```
I noticed https://github.com/sindresorhus/ky/pull/136 after I wrote the code but the PR seems not updated and ~backword incompatible (arguments order)~ so I decided to make this PR.
**Updated**

Pass input/options to beforeRequest/afterResponse hooks

---

index.js
test/browser.js

Move globals to getters to allow them to be mocked

---

index.js
readme.md
test/hooks.js

This PR adds support to return a Response from the beforeRequest hook and completely skip the HTTP request.
closes #157 
/cc @lidel

Allow returning `Response` from a `beforeRequest` hook

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js

Add `beforeRetry` hook just like [got](https://github.com/sindresorhus/got#hooksbeforeretry). I needed it to make sure that an access token is fresh prior to retry.
```typescript
export const client = ky.extend({
hooks: {
beforeRequest: [
async function(input, options) {
if (store.refreshRequired) {
await store.refresh();
}
if (store.isAuthorized) {
(options.headers as Headers).set(
'X-Authorization',
`Bearer ${store.accessToken}`,
);
}
},
],
beforeRetry: [
async function(input, options, errors, retryCount) {
if (store.refreshRequired) {
await store.refresh();
}
if (store.isAuthorized) {
(options.headers as Headers).set(
'X-Authorization',
`Bearer ${store.accessToken}`,
);
}
},
],
},
});
```

Add `beforeRetry` hook

---

index.js
test/main.js

Display a meaningful error to the user if they attempt to provide an invalid input (for example, a `Number`).
Resolves #174

Validate the `input` argument

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js
test/main.js
test/prefix-url.js

Closes #166
Closes #139
This PR:
- Aims to simplify Ky and solve some edge case issues and confusing behavior related to how our options are normalized and merged.
- Makes it so that internally, and within hooks, a [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance is now used as the source of truth instead of `input`. This replaces some of the bespoke logic that we've had for processing options. It also makes life easier for people using the `hooks` option, because they will receive a normalized `request`, whose behavior is more obvious and is well-specified by web standards. We can discuss whether the raw input should be available as well.
- Cleans up the separation betwen Ky options and `fetch` options internally, so there's a clear distinction and it's easy …

Use request to normalize options

---

readme.md

As @sholladay pointed out [here](https://github.com/sindresorhus/ky/issues/186#issuecomment-548250500), there is an issue with naming our IIFE variable `ky` due to the [temporal dead zone](http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified). 
We've decided to update the variable name in the documentation to `client`, which will now work.
Resolves #186

Improve example in documentation for using umd.js

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js
test/main.js
test/retry.js

Closes #167
Closes #182
Closes #187
This PR:
- Updates the `options` object passed to hooks so that _all_ Ky and fetch options are included. For context: in Ky v0.15.0 and earlier, a subset of Ky options were included in the `options` object (e.g. `prefixUrl` was included, but `throwHttpErrors` was not, without any clear justification).
- Loosens the validation of certain options so that hooks can pass their options (which are already _normalized_) to Ky to make a new request using the same options. For example, the `json` option now takes precedence over `body`, rather than being mutually exclusive with `body`. Additionally, `searchParams` can now be any value supported by [`URLSearchParams()`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams), which makes …

Pass all Ky options to hooks

---

index.d.ts
index.js
readme.md
test/main.js

Closes #193
This PR short-circuits the `.json()` body method and makes it return an empty string instead of parsing the body when the response status is 204 No Content. That way we avoid throwing a parse error due to an empty body.
Note that, as of this writing, we make no attempt to read the response body to check if it is empty, rather we trust the response status code from the server.

Avoid body method parse errors on 204 responses

---

index.js
test/main.js

Fixes #199 
This PR makes it possible to override the HTTP `accept` header that Ky sets by default when a [body method](https://developer.mozilla.org/en-US/docs/Web/API/Body#Methods) shortcut is used, such as `.json()`.

Allow overriding the default accept headers

---

index.js

Fixes #202 
This PR restores the global property lookup behavior that we had prior to PR #153, while still supporting the use case outlined in #151.
This fix is critical for anyone who mocks `window` in Node.js with any of our globals.

Fix global property lookup

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js

Hello,
This is related to the discussion from #185.
Summary of the PR:
- exported a new Symbol `NO_RETRY_SYMBOL`
- the Symbol can be imported & returned from a `beforeRetry` hook in order to abandon retries
- I'm unsure if an error should be thrown even if you have `throwHttpErrors` enabled
- added test & tsd
@sholladay @sindresorhus 
Thoughts?
Thank you!

Add ability to stop retries in `beforeRetry` hooks

---

package.json

**npm** just added a new [`npm fund` command](https://blog.npmjs.org/post/188841555980/updates-to-community-docs-more) in it's [v6.13.0](https://github.com/npm/cli/releases/tag/v6.13.0) release as part of the efforts to help out the OSS community.
This PR adds `funding` info to **ky** so that users depending on it can actually retrieve the funding url when they run `npm fund` in their projects.
Note: The funding information will only be available once a new version of the package is published to the npm registry.

Add package.json funding property

---

.editorconfig
package.json
test/headers.js

Porting headers re: #179 
Ported all tests that seemed relevant. These are the tests I didn't: 
- [does not set `accept-encoding` header when `options.decompress` is false'](https://github.com/sindresorhus/got/blob/62cdeec4838293bf61a80820b42ecc84c408c973/test/headers.ts#L60)
- This did set accept-encoding header. I think `options.decompress` doesn't exist on fetch, so I've omitted. 
- [stream as `options.body` sets `content-length` header](https://github.com/sindresorhus/got/blob/62cdeec4838293bf61a80820b42ecc84c408c973/test/headers.ts#L163)
- I'm not sure this is relevant for KY. If it is, I can add the test. 
- [throws on null value headers](https://github.com/sindresorhus/got/blob/62cdeec4838293bf61a80820b42ecc84c408c973/test/headers.ts#L186)
- This threw a 404 `HTTPError`, not a …

Port header tests from Got

---

index.d.ts
index.js
readme.md
test/main.js

Currently, falsey json values will get mistaken for an empty json value -- this makes the comparison more specific, and will match any json value other than `undefined`
Fixes #222

Fix handling of falsy value with the `json` option

---

index.js
test/browser.js

Fixes #217
I now clone the request before using it so that the body is not consumed and thus `fetch()` does not freak out when we try to reuse the request during retries, since it can still read the body.
I tried to write a test for this, however it seems to be hard to test in Node, as `node-fetch` doesn't seem to throw an error under the same circumstances that actual `fetch()` does in the browser. It should be possible to test this with Puppeteer, though I haven't tried.

Fix retries for requests with a body

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/browser.js
test/main.js
umd.d.ts

Closes #205 
This PR moves `HTTPError` and `TimeoutError` to properties of the default export rather than named exports.
CommonJS users can now just use `ky` instead of `ky.default`. Also eliminates a warning logged during the build.

Move named exports to properties of default export

---

index.d.ts
index.js
index.test-d.ts
readme.md
test/hooks.js

Add `response` to `beforeRetry` hook and change its parameter to a single object

---

index.js

Fixes #221 
This PR fixes a regression that was caused by a simple refactoring mistake in PR #180, which caused the request to not be aborted after a TimeoutError.
Unfortunately, while I did confirm that it works, I haven't figured out how to write a test for it. I was expecting that the abort operation would cause the client to hang up the connection, and I figured that would cause an `error` event on the test server's `request` object that I could watch for. But the abort doesn't seem to cause such an error to occur. I'm not familiar enough with the details of what AbortController does at the network connection / HTTP layer to know if there's anything else to look for.

Fix request cancellation on timeout

---

index.js
test/_require.js
test/browser.js
test/headers.js

We need to delete Content-Type header every time we create new instance of Request to properly set boundary in headers and in body.
Fixes #209

Delete `Content-Type` header for multipart requests

---

index.d.ts
index.test-d.ts

Add TimeoutError and HTTPError to ky TypeScript namespace

---

index.d.ts

Fixes #240 
This PR removes a vestigial part of our `NormalizedOptions` TypeScript interface that is no longer necessary and causes issues for TypeScript users who pass the `headers` option as a plain object (as opposed to a [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance) and then receive it inside of a hook. The definition of `headers` now comes from `RequestInit`.
For context, in older versions of Ky, we aggressively normalized the options object passed by the user before running any hooks. However, newer versions of Ky try to avoid such normalizations in favor of constructing a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance and passing that around, as it does a lot of the work for us, including normalizing the headers.

Fix the NormalizedOptions.headers TypeScript type

---

index.js
test/http-error.js

Fixes https://github.com/sindresorhus/ky/issues/248
This ensures HTTPError will always have a defined message in various situations.

Ensure HTTPError always has a defined message

---

index.js
test/headers.js

Closes #260 
_This is a redo of PR #261, because the tests on that PR are exhibiting some unexpected behavior that I haven't been able to determine the root cause of, but are most likely git related, possibly even a backend issue with GitHub._

Fix headers construction in old browsers

---

index.js
package.json
test/browser.js
test/fetch.js
test/helpers/with-page.js

Closes #236 
This PR aims to solve the last problem I am aware of related to URL resolution in Ky. Historically, we've used the WHATWG URL constructor (`new URL()`) in various situations to parse, resolve, and modify URLs. But it's been highly problematic because that API only supports absolute URLs and throws an error if given anything else. It's difficult for Ky to know what base URL to resolve against just to satisfy that constraint, even in browsers (e.g. web workers do not have access to `document.baseURI`), not to mention Deno, Node, React Native, and other environments. This makes `new URL()` quite a footgun.
I have chipped away at these kinds of URL resolution problems over time (e.g. #59 and #180). These days, we mostly rely on the much better behaved `Request` class which _does_ …

Add support for relative URLs and searchParams even in non-browsers

---

index.d.ts
index.js
readme.md
test/fetch.js

As requested in #269, this PR adds the ability to pass a `fetch` option when creating a ky instance.
This allows to use custom fetch implementations like [isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch) or when using SSR in some frameworks (Sapper in my case).
Fixes #269

Add option for custom `fetch` implementation

---

index.d.ts
readme.md

Closes #253 
This PR updates the documentation to clarify that, by default, `throwHttpErrors: true` does _not_ throw for redirects because the redirects are followed beforehand. It's possible to treat a redirect as an error, too, by setting the `redirect` option to `'manual'`. (Or you could set `redirect` to `'error'`, but then the error will be thrown by `fetch` instead of Ky, and thus it won't be a `ky.HTTPError`).

Clarify `throwHttpErrors` and redirect interaction 

---

index.d.ts
index.js
readme.md
test/hooks.js

Fixes #251 
Fixes #275 
The PR fixes some problems with hooks caused by how we handle responses:
- Most importantly, it ensures that `beforeRetry` hooks get called as expected in case of a network error where no response was received. Previously, if a network error occurred, Ky would attempt to clone a non-existent response, causing an exception immediately before the `beforeRetry` hook, meaning it wouldn't be called. The simplest fix, which I've implemented here, is to just remove the `response` parameter (which was merely a shortcut) and make people use `error.response` instead, which IMO is actually a bit clearer anyway, in that it is obvious the response may be `undefined`. There are some other possible ways to fix this... we could make it a getter, or use `error.response && …

Fix handling of network errors for `beforeRetry` hook

---

test/browser.js

Fixes test which started failing with [Fix handling of network errors for `beforeRetry` hook (#276)](https://github.com/sindresorhus/ky/commit/9876da129c216b99ad9f5760d38ba0ed1876d20e).
As far as I could tell, `node-fetch` is not to blame for this. I looked into its source code and could not find a matching discriminating line which would yield this error message (i.e. with the seemingly added prefix). I checked both current version and the one which is used here.
Since the tests are run with `puppeteer` I think it's Chromium's native `fetch` which is used. The `global.fetch` in [_require.js](https://github.com/sindresorhus/ky/blob/master/test/_require.js) is _not_ used for these tests (I simply tried to replace it with a function which would `throw` immediately, without any effect).

Update `AbortError` message in the tests

---

index.d.ts
index.test-d.ts
test/browser.js

Expose `TimeoutError#request`

---

index.d.ts

Removed the line in `index.d.ts` that caused errors when trying to use the library in Deno. This resolves #294 and fixes #224.
I have tested it on Deno 1.5.1 with Typescript 4.0.3 and it seems to work fine.
@sholladay mentioned that they want someone proficient in Typescript to analyze potential drawbacks from doing that, so I'm leaving it up to discussion since I'm far from an expert 😅

Fix Deno and React Native compatibility

---

index.js
test/browser.js

(See commit messages.)
For instance, the catch block in the [example in the README](https://github.com/sindresorhus/ky#cancellation) would not catch the AbortError if an onDownloadProgress callback were passed to ky.
I'm not entirely sure about the Chromium bug. With the patches applied in my project that uses ky, I could get Firefox to throw an AbortError, so I suspect https://bugs.chromium.org/p/chromium/issues/detail?id=817687 is not fully fixed.

Fix aborting when `onDownloadProgress` throws an exception

---

index.d.ts
index.test-d.ts

Fix support for `ky.stop` as return type in `BeforeRetryHook` TypeScript type

---

.github/workflows/main.yml
.gitignore
index.js
package.json
readme.md
test/browser.js
umd.d.ts

I have decided to target Node.js 12 and drop the UMD build. Node.js 10 will be obsolete in a few months anyway.
This lets us go full ESM, which reduces the chances of [problems](https://twitter.com/bradleymeck/status/1346466891070664704) as some bundlers cannot handle `exports` in package.json.

Require Node.js 12 and drop UMD build

---

index.d.ts
index.test-d.ts

Fixes #289 and fixes #288. The latter can be fixed by #307, but it doesn't include moving arguments that `BeforeRetryHook` receives to a separate object that can later be used to declare `beforeRetry` hooks outside of `ky.create` declaration or actual request.

Fix `BeforeRetryHook` and `NormalizedOptions` TypeScript type definitions

---

index.d.ts
index.js
index.test-d.ts
readme.md

Add `request` and `options` to `HTTPError`

---

index.d.ts
readme.md

Fixes #290. I would also like to add `console.warn` in shortcut methods, such as `.json()` and `.text()` that would display a warning when ky.stop is returned and these methods are used. Maybe a lazy solution to check if this `result` is not `undefined` could work:
https://github.com/sindresorhus/ky/blob/d9760294875b46263265fa4a4c470edfb3347295/index.js#L338
I can definitely add a check that it's not `undefined` to prevent those from throwing `TypeError` and to make them silently return `undefined` instead. The question is: is it guaranteed that if `result` is `undefined`, this was caused by `ky.stop`? If yes, I could also add `console.warn` in the same place where this check for `result !== undefined` is performed.

Improve docs for `ky.stop`

---

readme.md

Closes #302
At the moment, Skypack generally has better TypeScript support than other CDNs, and thus is probably the best choice for most Deno users.
I would still recommend unpkg for everyone else, as in my experience unpkg is faster and less buggy.

Update recommended CDN for Deno users

---

package.json
test/browser.js
test/helpers/with-page.js

Making browser tests great again!
This PR makes big improvements to the reliability, install size, install time, and performance of the browser tests by switching from [Puppeteer](https://developers.google.com/web/tools/puppeteer/) to [Playwright](https://playwright.dev/). it also re-enables these tests in CI, as this fixes the test flakiness we've experienced for a long time. Further performance gains could likely be had by sharing a browser instance across tests and using Playwright's [contexts](https://playwright.dev/docs/core-concepts#browser-contexts) feature for isolation (as shown [here](https://playwright.dev/docs/test-runners#ava)), but the tests are so fast now I didn't even bother. Re-installs are speedier as well, because Chromium is cached by Playwright.
Microsoft is …

Switch from Puppeteer to Playwright for reliable and concurrent browser tests

---

index.js
test/_require.js
test/fetch.js
test/headers.js
test/hooks.js

As of https://github.com/sindresorhus/ky/pull/315, Ky requires the fetch related APIs to be true globals on `globalThis`, as opposed to dynamically looking them up on various namespaces. Thus the list of globals and getters for them no longer serves a purpose.

Simplify global variable usage

---

index.js
test/fetch.js
test/main.js

When providing a raw searchParams string, currently ky will pass it through `new URLSearchParams()` which has the result of mangling it in places where it is perfectly valid. A simple example is a querystring like `a&b=` (which is the output of `qs.stringify({ a: null, b: '' }, { strictNullHandling: true })`) is changed to `a=&b=` which semantically has a different meaning (a and b are both empty string).
This change is pretty simple, if a user provides a string don't mess with it - use it directly. This is a breaking change and should be released as a major if landed. I added one new test for a specific case with null values and also had to update other tests.

Don't mangle user-provided `searchParams` string

---

source/errors/HTTPError.ts
test/browser.ts
test/hooks.ts
test/http-error.ts

This PR aims to provide a clearer error message to the user when an `HTTPError` occurs, by adding a description and showing both the status code and status text, when available.
Perhaps the best example of how this helps is where the response has an unusual status code, such as 0, but there is no status text, as is the case when HTTP/2 is being used.
Before:
```
HTTPError: 0
```
After:
```
HTTPError: Request failed with status 0
```
Happy to bikeshed the phrasing. Could change "failed with status" to "failed with response status", for example. Also on the fence about "an unknown error" vs "an unknown status" vs "an unknown response error", etc.

Improve HTTPError messages

---

source/core/Ky.ts
test/main.ts

Closes #246 
This PR aims to fix some unintended behavior for people who use the `throwHttpErrors: false` option. Previously, if the method was retriable, _all_ operational errors would be suppressed, including network errors and timeout errors, not just HTTP status code errors. Now, the option _only_ suppresses errors of the `ky.HTTPError` class, which are thrown when a response is received with a non-2xx status code.

Fix throwHttpErrors: false suppressing non-HTTP errors

---

source/utils/merge.ts
test/main.ts

Closes #324
This PR fixes how the `searchParams` option is handled in `ky.create()` and `ky.extend()` so that the user's expected search params are used. Previously, we were inadvertently adding a `headers` search param in some cases.

Fix merging of searchParams in create()/extend()

---

source/core/Ky.ts
source/types/options.ts

I narrowed the type to fix a TypeScript error when the option was passed to the URLSearchParams constructor, but obviously it was a mistake as we don't want any breaking changes. We might want to reconsider in the future to be more compliant with the official types.
I've added a manual `as` to the constructor as a fix.
---
Fixes #343

Fix `searchParams` option TypeScript type

---

package.json

`ky@0.28.0` can't be used in react-native apps anymore due to a missing main field in `package.json`.
Metro does provide configuration options to support extra "main" fields but adding `"exports"` there breaks as other packages start to use this field instead of their `"main"` (not sure why, as it is expected to be an ordered check, maybe a metro-related bug of the `"exports"` key handling when in object form). Haven't found a way to make it work except manually patching the ky's package.json.
```
error: Error: While trying to resolve module `ky` from file `~/foo/src/services/pumalocal/client.ts`, the package `~/foo/node_modules/ky/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`~/foo/node_modules/ky/index`. …
```

Restore `main` field in package.json

---

package.json
source/core/Ky.ts

Fix incompatibility with New Relic

---

source/index.ts

Since version 0.28 the types exported by ky seem to have been reduced. Our codebase relies on ky hooks and we used to be able to import the hook method types from ky in TypeScript.
```typescript
import { AfterResponseHook, BeforeRequestHook } from 'ky';
```
This PR adds the missing exports for the hook methods back to the index including the new retry hook method.

Fix missing hook method types for TypeScript

---

readme.md

This PR aims to fix the usage instructions and CDN import URL for those without a bundler, which PR #330 broke.
CDN users need to import `distribution/index.js` instead of `index.js`.
I also changed the CDN host from jsdelivr to unpkg, which isn't strictly necessary so long as the path is updated, but jsdelivr seems to be buggy. It's incorrectly caching `index.js` from previous versions and returning it, even though that file doesn't exist anymore.

Update instructions for use without a bundler

---

readme.md

Small nitpick, but the way GitHub markdown anchor tags work is that they ignore punctuation.
The correct url is https://github.com/sindresorhus/ky#kystop

Fix broken anchor link in readme

---

readme.md
source/types/options.ts

How retry behaves in conjunction with timeout was not clear from the readme (see https://github.com/sindresorhus/ky/discussions/279), so improved this.

Improve documentation for retry and timeout

---

readme.md
source/core/Ky.ts
source/types/options.ts
test/headers.ts

Closes #369
This PR adds logic to ensure that `options.headers` takes precedence over our own default for the `Content-Type` header when the `json` option is used. This allows the user to send a JSON request with a content type other than `application/json`.

Allow overriding `Content-Type` header for JSON requests

---

source/index.ts

The `BeforeRetryState` is the only type not exported from types/hooks.
**Background**
We are doing an upgrade to TS 4.7, in our code we were importing the `BeforeState` directly like this:
```ts
import { BeforeRetryState } from 'ky/distribution/types/hooks';
```
However after upgrading to TS 4.7, were can no longer can import the `BeforeRetryState` type directly:
And since it's not export the the following does not work either:
So we want the `BeforeRetryState` too also be exported, so that we can import it directly e.g.:
```ts
import { BeforeRetryState } from 'ky';
```

Export BeforeRetryState from types/hooks

---

readme.md
source/core/Ky.ts
source/types/ResponsePromise.ts
test/main.ts

Following the discussion in this Issue( #415 ), I changed the `.json()` behavior.
When response body is empty, `.json()` now returns an empty string (`''`) instead of throwing an exception(`FetchError: Invalid JSON`).
>  I was thinking in terms of whether it's reasonable for a given status code to have an empty body. But I'm sure there are plenty of implementations out there that return an empty body with a 200 or other success codes. Maybe we should just allow that for convenience sake.
https://github.com/sindresorhus/ky/issues/415#issuecomment-1007626969
> When Content-Length is 0 or is missing, body must be returned as an empty string.
https://github.com/sindresorhus/ky/issues/415#issuecomment-1228718284
Close #415 
Close #430 
- json() with empty response body
- json() with Invalid …

Parse empty response bodies without throwing

---

source/core/Ky.ts
test/main.ts

fixes sindresorhus/ky#463
Here is some relevant documentation about the `Transfer-Encoding` header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding , specifically when a `chunked` value is set for that header:
> `chunked`: Data is sent in a series of chunks. The [`Content-Length`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header **is omitted in this case** [...] [emphasis added]
This is in contradiction to an implicit assumption seemingly made in https://github.com/sindresorhus/ky/pull/459 that a `Content-Length` header will always be set to some non-zero value if there is content in the response body.
The logic change in this PR returns a blank string for `.json()` only if the `Content-Length` header is `'0'` or missing (per …

Don't return empty string for .json() if Transfer-Encoding is chunked

---

source/core/Ky.ts

fixes #463 (third attempt! #464 was merged but does not fully solve the problem; #465 was closed without merge)
Many, many thanks to @0f-0b for [pointing out](https://github.com/sindresorhus/ky/issues/463#issuecomment-1297395043) what seems sort of obvious in retrospect, that the best way to do this is probably to read the actual response body (or lack thereof), which is what this PR does, rather than trying to use the HTTP headers to figure out whether the response contains a body or not.
Well, maybe it's not so obvious, actually, because there _might_ be downsides to calling `response.clone()` with respect to processing speed and/or memory usage. (We have to clone the response (or, at least, do something special) because once we read the response body, we can't read it again. I got the …

Return empty string from json() if byteLength of cloned response is 0

---

readme.md

The Skypack CDN recommended in the README does not seem to be well maintained, with the [service status page](https://status.skypack.dev/) being 404, so changed to use [esm.sh](https://esm.sh/).
> reference: https://github.com/skypackjs/skypack-cdn/issues/329
I think esm.sh is the best choice for migration since it has the same extensive Typescript type support as Skypack.

Update recommended CDN for Deno

---

.vscode/settings.json
readme.md
source/core/Ky.ts
source/types/retry.ts
source/utils/normalize.ts
test/retry.ts

I saw in the source code that the retry backoff function is hardcoded and exponential. However, I wanted to customize it.
Fortunately I also found the open issue addressing this limitation.
To start simple, I added a `backoffLimit` so that you can cap the delay that is exponentially growing. After 5 or so retries the delay becomes so large that the user will give up anyway.
Setting the limit to for example 1000 in combination with 60 retries will change the behavior into polling for 1 minute (my use case).
I had some trouble testing the delay because the calculate function is private and I didn't find a way to extract this information from the `ky` instance or response.
So I did some perf measurements to test the delays.
If you are happy with the PR so far, I will implement the …

Add retry.backoffLimit option

---

.github/workflows/main.yml
test/browser.ts
test/helpers/with-page.ts

The browser tests were flaky due to the reason that the `server.close()` call was slow sometimes due to open connection kept alive, which is default server behaviour.  Resulting in false pending tests assertiions that are actually finished but never finish and times out due to that the server is not closed within the expected timeout.
* Added middleware that ensures that the connections are closed after response is sent (@see stackoverflow [here](https://stackoverflow.com/a/13554590/620479))
* Added `beforeEach`  and `afterEach` methods that setups and closes server for each test.
* All the tests are also now serial which is needed since we only have one server that is setup and teardown per test as mentioned above (also playwright is not that good with parallell running browsers either …

Fix flaky browser tests

---

source/errors/DOMException.ts
test/main.ts

When throwing DomException it should provide `AbortError` name to the DomException constructor as specified in the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort)
The PR also includes fallback to use of `Error` class where the `name` property is overridden.
This PR addresses and closes the following issue #470

feat: Throw DomException with name AbortError

---

source/core/constants.ts

```
~/Developer/open-source
❯ node -v
v18.14.0
~/Developer/open-source
❯ node --no-experimental-fetch
Welcome to Node.js v18.14.0.
Type ".help" for more information.
> ReadableStream
[class ReadableStream]
> Request
Uncaught ReferenceError: Request is not defined
>
```

fix: check `Request` before executing

---

source/core/constants.ts

This was added in 0b141f1725442039a439b683d32d42e9b9d52559 as a fix for #452.
This replaces the patched-in `a.com` with a domain which is reserved and guaranteed to not resolve to an actual address as per https://www.rfc-editor.org/rfc/rfc2606.

fix: replace placeholder a.com with unresolvable emtpy.invalid (RFC 2606)

---

readme.md
source/core/Ky.ts
source/types/options.ts
source/types/retry.ts
source/utils/normalize.ts
test/helpers/with-performance-observer.ts
test/retry.ts

Related to option (2) to #509 
- add `delay` function to `RetryOptions` object
- add test for using `delay`

Add retry.delay option to control the time between retries

---

.github/workflows/main.yml
package.json
source/core/constants.ts
source/types/request.ts
source/utils/options.ts
test/browser.ts
test/helpers/with-page.ts

Turns out that the read-only `body` property of the Request interface [is not [yet] supported by Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Request/body#browser_compatibility) which causes #539.
Changes:
- Add functionality to run same test in multiple browsers including Firefox (⚠️ slows down CI by about 1 minute; ~15% slower)
- Check [Request constructor options](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request#options) explicitly.
Fixes: #539 (introduced in #536)

Fix multipart boundary mismatch

---

source/core/Ky.ts
source/types/options.ts
source/utils/merge.ts
test/headers.ts

Otherwise TypeScript fails with `skipLibCheck: false`, `exactOptionalPropertyTypes: true` and no `DOM`:
```
Error: node_modules/ky/distribution/types/options.d.ts(226,18): error TS2430: Interface 'NormalizedOptions' incorrectly extends interface 'RequestInit'.
Types of property 'credentials' are incompatible.
Type 'RequestCredentials | undefined' is not assignable to type 'RequestCredentials'.
Type 'undefined' is not assignable to type 'RequestCredentials'.
Error: node_modules/ky/distribution/types/options.d.ts(16,29): error TS2552: Cannot find name 'HeadersInit'. Did you mean 'KyHeadersInit'?
Error: node_modules/ky/distribution/types/options.d.ts(160,21): error TS2552: Cannot find name 'RequestInfo'. Did you mean 'RequestInit'?
Error: …
```

Make types compatible with both DOM and Node.js

---

source/core/Ky.ts
test/browser.ts
test/hooks.ts
test/retry.ts

Fixes #528 (actual retry count being 1 less than the specified retry limit).
This could be seen as a breaking change for projects using the +1 workaround.
The [main issue](https://github.com/sindresorhus/ky/blob/3cf50649ac2a9d5230ebcff94fa58b63a77781dc/source/core/Ky.ts#L209-L211) was `_retryCount` first being incremented, then being checked if it's less than `_options.retry.limit`, resulting in an off-by-one which is fixed with a less-or-equal comparison instead.
Re-enabled retry count test, and fixed other misconfigured tests which either explicitly failed or had silent bugs related to this. All tests pass with Node v18.18.0 (v18.18.2 breaks a number of tests, and Ava can't use custom loaders with v18.19 or v20+ making testing impossible).
EDIT: CI seems to fail since it doesn't extend …

Fix #528 (retry count 1 less than retry limit)

---

source/core/Ky.ts
source/types/options.ts

This PR comes to fix the Cloudflare workers issue mentioned here with the solution:
https://github.com/sindresorhus/ky/issues/366#issuecomment-1670435774
Fixes #366

fix: support cloudflare workers

---

source/core/Ky.ts
source/core/constants.ts
source/types/options.ts
tsconfig.json

https://github.com/sindresorhus/ky/pull/559 undid the fix in https://github.com/sindresorhus/ky/pull/543. Added `exactOptionalPropertyTypes` to `compilerOptions` to prevent this from happening again, seems pretty low-impact. It should be okay to pass `undefined` to `credentials` and other options, but this is an upstream problem (see `RequestInit` in `undici-types/fetch.d.ts`).
The build was failing on TS 5.4 because there's a `priority` in `RequestInit` now.

Fix `exactOptionalPropertyTypes`, fix TypeScript 5.4

---

source/types/hooks.ts

I saw these typos while doing some debugging, so I figured I should go ahead and submit a fix!

fix a small typo in a JSDoc comment

---

source/types/request.ts

When using Ky with Node, TypeScript will run into compilation error regarding types required by `UndiciRequestInit`. This is because `@types/node` does not yet provide these types, and they are not imported from `undici-types` either. The latter would not even be possible to keep Ky usable with browsers.
This happened to work in the project, because `@sindresorhus/tsconfig` includes `DOM` in the libs section. In most Node applications, the DOM lib should not be there and clashes with Node types. One way to circumvent this is to add `skipLibCheck: true` to `tsconfig.json`, but this is not a good solution.
This commit adds the needed types until `@types/node` imports the missing types and adds them to globals. After that, all "Undici" types from the request types should be removed.

Fix request types for use with Node

---

readme.md
source/core/Ky.ts
source/core/constants.ts
source/types/options.ts
test/main.ts

When sending an HTTP request, this option allows the user to specify how the request data should be serialized as a string.
For example, it will be useful when users want to change the default serialization behavior using `JSON.stringify(_, replacer)`.
```typescript
import ky from 'ky';
import { DateTime } from 'luxon';
const json = await ky('https://example.com', {
stringifyJson: data => JSON.stringify(data, (key, value) => {
if (key.endsWith('_at')) {
return DateTime.fromISO(value).toSeconds();
}
return value;
})
}).json();
```

feat: add support for `stringifyJson`

---

test/browser.ts

Hello, I noticed a test that was commented out in browser.ts and fixed it.
When I uncommented it, I got a `ReferenceError: __name is not undefined` on playweight at the following location
```
const decodeUtf8 = (array: Uint8Array) => String.fromCodePoint(...array);
```
On playweight, it is executed as follows
```
const decodeUtf8 = __name((array) => String.fromCodePoint(...array), "decodeUtf8")
```
I found out that this was due to an optimization option `keepNames` in vite.
refs: vite/pull/2376#issuecomment-805285480, esbuild/issues/2605#issue-1404600925
In this repository, it seems to be happening only within playweight. I don't think there is any need to make it a function except for readability, so I fixed it so that it doesn't create a function.
Just to be sure, I tried it …

Fix `onDownloadProgress` test commented out in test/browser.ts

---

source/errors/HTTPError.ts
source/errors/TimeoutError.ts
test/browser.ts
test/hooks.ts
test/http-error.ts

Closes #592
This PR aims to make the error messages from Ky's `TimeoutError` and `HTTPError` more helpful by including the request method and URL.
Before:
```
TimeoutError: Request timed out
```
```
HTTPError: Request failed with status code 400 Bad Request
```
After:
```
TimeoutError: Request timed out: POST https://localhost:3000/
```
```
HTTPError: Request failed with status code 400 Bad Request: POST https://localhost:3000/
```

Add request method and URL to error messages

---

source/core/constants.ts

Improve detection of streaming request support (#581)

---

source/core/Ky.ts

Fixes #435
This PR makes it so that Ky only uses a cloned request when it has to, for retries, but not the initial fetch.
This will improve reliability in environments where `request.clone()` has limitations or is poorly implemented.

Fetch with an uncloned request when possible

---

source/core/Ky.ts
test/retry.ts

Closes #390 
This PR aims to align our retry delay semantics with `setTimeout()` and similar, i.e. `0` means retry immediately, not cancel.
This applies to all delay sources, including `Retry-After`.

Retry request even if retry delay is zero

---

readme.md
source/errors/HTTPError.ts
source/errors/TimeoutError.ts
source/index.ts
source/types/hooks.ts
source/types/request.ts
test/hooks.ts

- introduces `KyRequest` which, like `KyResponse`, adds `json()` convenience method for extracting JSON with an expected TypeScript type
- update API `Request`/`Response` usages to expose `KyRequest`/`KyResponse` to `ky` consumers so that they may use the `json()` convenience method in more scenarios (`HTTPError`, `TimeoutError`, and hooks)
Closes #584

Use KyRequest and KyResponse types in errors

---

readme.md
source/index.ts
source/types/ky.ts
test/main.ts

callback function receives parent's default options to allow extended instance to refer to modify parent options
Closes #586

Add support for passing a function to ky.extend()

---

source/core/Ky.ts
test/main.ts

Currently, ky ignores `AbortSignal` when it's provided as part of a `Request` object.
This PR modifies the `Ky` class to properly extract and respect the `AbortSignal` from `Request` objects. It ensures that signals are handled consistently whether they're provided directly in the options or as part of a `Request` object.

Fix signal handling for Request objects

---

source/core/Ky.ts

This PR is just internal housekeeping. No user-visible changes are intended.
The `input.credentials` will be used automatically by `fetch()` if `options.credentials` is not defined, so copying it over manually is unnecessary.

Remove unnecessary setting of `credentials` option

---

readme.md
source/core/Ky.ts
source/types/options.ts
test/retry.ts

Closes #608
This PR adds automatic handling for non-standard rate limiting headers that are used by some APIs (e.g. GitHub and Twitter) instead of `Retry-After`.
The following headers are now supported as a fallback for `Retry-After`:
- `RateLimit-Reset` as proposed by https://www.ietf.org/archive/id/draft-polli-ratelimit-headers-05.html#section-3.3
- `X-RateLimit-Reset` as implemented by GitHub
- `X-Rate-Limit-Reset` as implemented by Twitter
Dates, timeouts (delta seconds), and timestamps (seconds since epoch) are all supported.
Timestamps in milliseconds are not currently supported, as none of the popular APIs use it.
More variants are discussed here: https://github.com/ietf-wg-httpapi/ratelimit-headers/issues/25

Add support for the `RateLimit-Reset` header

---

readme.md
source/core/Ky.ts
source/errors/HTTPError.ts
source/types/ResponsePromise.ts
source/types/ky.ts
source/types/request.ts
source/types/response.ts
test/http-error.ts
test/main.ts

Closes #615
Closes #485
Relates to #312 
This PR adds support for an optional TypeScript generic type parameter in all request methods, passes it through the request, response promise, and response, and into `.json()`, so that users have more flexibility in where and how they type their JSON objects.
All of the following forms are supported:
- `ky<T>()`
- `ky.get<T>()` (all methods)
- `ky().json<T>()`
- `(await ky()).json<T>()`
The `HTTPError` class has similarly been updated and passes its type parameter through to `error.response.json()`. See #615 for an example of how this could be used.

Add JSON generics to ky() and HTTPError

---

source/types/request.ts

`NodeJS.ArrayBufferView` type annotation fails when compiling for browsers. For details see #622 
closes #622

Remove `NodeJS` type prefixing

---

readme.md

I was a little baffled by the two "Download" links as I made #612. Turns out they are pointing to an older version of ky (0.16.2 according to the header of https://cdn.jsdelivr.net/npm/ky/index.min.js). This pull request removes them since they are long outdated.
Also changed the jsdelivr link below to a direct link usable in `<script src="...">`, in line with the unpkg and esm.sh link below.

Revise CDN links in readme

---

source/types/ky.ts

Just a small tweak on the `ky.create()`. I know it's also possible to use the global `ky` instance, but just in case one wants to use this factory method instead.

Mark `ky.create()` options as optional in public types

---

source/core/Ky.ts

Fixes #648
This removes an unnecessary response clone that was used in body method shortcuts, such as `ky().json()`, which caused the original response to be fully buffered and never consumed.

Fix memory leak from cloned responses

---

source/core/Ky.ts
test/main.ts

ky does not seem to abort a request if the signal was aborted before the request was triggered ([ref](https://github.com/sindresorhus/ky/issues/660)). 
We fix this by calling the `throwIfAborted()` method on the original signal.

fix: throw early if signal is aborted before request is triggered

---

source/core/Ky.ts
test/methods.ts

Fix `options.method` (where `options` has the `NormalizedOptions` type) being `undefined` when no method is provided.
Fixes #670.

Fix options.method being undefined in normalized options

---

readme.md

Clarifies that some errors (especially network errors) will not be an instance of HTTPError and not contain a response. Language copied from `hooks.beforeRetry`.
I believe it is important to reiterate this at the HTTPError level, as it is not immediately intuitive that all errors wouldn't be an instance of HTTPError.
Whether all errors *should* be an instance of HTTPError is up to debate (and I gather is actively under consideration in a number of issues/discussions), and is outside the scope of this PR.

Update readme.md to clarify HTTPError

---

source/core/Ky.ts

Fixes #690 
Prevents requests from hanging in certain cases by
1. Waiting until all retries are complete before cleaning up the final retry clone, rather than cleaning up each retry clone after each retry.
2. Cleaning up the retry clone even if there is an error.

Improve reliability of cloned request cleanup

---

.github/workflows/main.yml
test/headers.ts

This PR ensures that the CI tests run on all [currently supported versions](https://nodejs.org/en/about/previous-releases#nodejs-releases) of Node to help catch upstream bugs, like the one discussed in #689.

Add Node 20 and latest to CI tests

---

source/core/Ky.ts

This is a potential fix for #719. Even if it's not, it's still a nice simplification. So for that reason, I'm not going to wait for OP of #719 to test it out first.
Since it's not reproducible, I was not able to add a test.

Fix race condition issue with `.json()`
