sindresorhus/ky

index.js
=> Minor code refactoring

index.js, readme.md, test.js
=> added hooks modeled after Got

test/main.js
Up the code coverage to 100%. :)
=> Add a test case for extend with deep array

index.js, test/main.js
=> Add type assertion for `.extend()` argument

index.js, readme.md, test/retry.js
=> Respect the `Retry-After` header when calculating retry delay

readme.md
=> Add FAQ answer on how to use Ky without a bundler

readme.md
=> Remove slash in prefixUrl example

index.js, readme.md, test/hooks.js, test/main.js, test/methods.js
=> Document using FormData

index.js, readme.md, test/_require.js, test/main.js
Fixes #134 
Followed up on https://github.com/sindresorhus/ky/issues/134#issuecomment-491044682 and also added a test for it.
=> Fix passing a `Request` instance as input

index.d.ts, index.js, readme.md, test/retry.js
=> Make the `retry` option more powerful

package.json
=> Use `prepare` in npm run script

index.d.ts, index.test-d.ts
`BeforeRequestHook` types got out of date.
=> Update typings for BeforeRequestHook

index.d.ts, readme.md
=> Document `prefixUrl` reasonings

package.json, test/browser.js
More detailed test that reproduces the bug described in #209.
=> Add failing test for using FormData with searchParams

index.d.ts, index.js, index.test-d.ts
This is a fix #266 I opened earlier.
I'm not a Ky internal expert, so it's opened to discussion, improvement and suggestions.
=> Add `Request` to `TimeoutError`

index.d.ts, index.js, readme.md, test/main.js
fixes https://github.com/sindresorhus/ky/issues/254
Duplicated https://github.com/sindresorhus/ky/pull/257 due to "travis glitch" https://github.com/sindresorhus/ky/pull/257#issuecomment-657292168
Closes #257
=> Add `parseJson` option

readme.md
=> Mention `ky-hooks-change-case` in the readme

index.js
=> Replace `Reflect.has()` with the `in` operator

package.json, test/browser.js, test/fetch.js, test/headers.js, test/hooks.js, test/http-error.js, test/main.js, test/methods.js, test/prefix-url.js, test/retry.js
=> Make the package a module type

source/core/Ky.ts, test/browser.ts
=> Fix Response details are lost when using onDownloadProgress

source/core/Ky.ts, test/browser.ts
=> Fix copy response body with 204 status code when use onDownloadProgress

source/core/Ky.ts, source/core/constants.ts
=> fix(#450): Duplex Request param needed in Chrome@105

readme.md, source/types/hooks.ts
`statusCode` doesn't seem to exist
=> Fix incorrect doc and add example

readme.md
ky is no longer single-file since https://github.com/sindresorhus/ky/releases/tag/v0.28.0 - it probably makes sense to clarify this if people somehow do want a single-file package and suprised to find ky actually is not 😅
=> readme nitpicking

.github/workflows/main.yml, package.json, source/core/Ky.ts
=> Fix memory leak, clean up body streams after retry

source/core/Ky.ts, source/core/constants.ts
I took the idea from https://github.com/sindresorhus/ky/pull/701#issuecomment-2944963709. 
I think it follows the support policy explained in https://github.com/sindresorhus/ky/issues/688, and the code fits with the rest.
=> Test support of AbortSignal.any()

readme.md, source/core/Ky.ts, source/core/constants.ts, source/types/ResponsePromise.ts, test/bytes.ts
=> Add `.bytes()` shortcut

test/browser.ts
=> Add test for request cancellation

readme.md, source/core/Ky.ts, source/index.ts, source/types/ky.ts, source/utils/type-guards.ts, test/hooks.ts
Introduce type guards to enhance error handling in the Ky client, allowing for more precise identification of HTTP and timeout errors. This improves the robustness of error management in the application.
closes #742
=> Add type guards for errors
